spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_liquibase
    username: postgres
    password: postgres

logging:
  level:  #vado ed eliminare gli ultimi due livelli di di log che in questo momento non servono e appesantirebbero solo i log
    root: INFO         #con info abbiamo informazioni quasi sempre utili

gym:
  schedule:
    opening: "07:00:00"
    closing: "23:59:59"

statistics:
  certificates:
    expiring-soon: P30D
  subscriptions:
    expiring-soon: P30D
