spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: postgres
    password: postgres

gym:
  schedule:
    opening: "07:00:00"
    closing: "23:59:59"

statistics:
  certificates:
    expiring-soon: PT30D
  subscriptions:
    expiring-soon: PT30D
